# specificerar versionen av docker-compose
version: "3.8"

# definierar tjänsterna/containrarna som ska köras
services:
  # definierar frontend-tjänsten
  # vi kan använda valfritt namn för tjänsten, standardnamn är ofta "web" för frontend
  web:
    # depends_on anger att tjänsten är beroende av en annan tjänst
    # här specificeras att web är beroende av api-tjänsten
    # detta innebär att api-tjänsten startas innan web-tjänsten
    depends_on: 
      - api
    # anger byggkontexten för web-tjänsten
    # detta är katalogen där Dockerfilen för web-tjänsten finns
    build: ./client
    # anger portarna som ska exponeras för web-tjänsten
    # första numret är porten på värddatorn
    # andra numret är porten inne i containern
    ports:
    # portmappning för web-tjänsten
    # #################################################################
    # VIKTIGT frontend package.json script --> "dev": "vite --host",
    # #################################################################
      - 5173:5173
    # anger miljövariabler för web-tjänsten
    # dessa miljövariabler kommer att vara tillgängliga i containern
    environment:
      VITE_API_URL: http://localhost:3007

    # detta är för docker-compose watch-läge
    # allt under "develop" kommer att övervakas av docker-compose watch och utföra åtgärden som anges
    develop:
      # specificerar filer som ska övervakas för ändringar
      watch:
        # övervakar ändringar i package.json och package-lock.json och bygger om containern vid ändringar
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        # övervakar ändringar i frontend-mappen och synkar ändringarna i realtid med containern
        - path: ./client
          target: /app
          action: sync

  # definierar api-tjänsten/containern
  api: 
    # anger byggkontexten för api-tjänsten
    build: ./server
    
    # anger portarna som ska exponeras för api-tjänsten
    # första numret är porten på värddatorn
    # andra numret är porten inne i containern
    ports: 
      - 3007:3007

    # aktiverar docker-compose watch-läge för api-tjänsten
    develop:
      # specificerar filer som ska övervakas för ändringar
      watch:
        # övervakar ändringar i package.json och package-lock.json och bygger om containern och bilden vid ändringar
        - path: ./server/package.json
          action: rebuild
        - path: ./server/package-lock.json
          action: rebuild
        
        # övervakar ändringar i backend-mappen och synkar ändringarna i realtid med containern
        - path: ./server
          target: /app
          action: sync
